name: Auto Commit Workflow
on:
  schedule:
    # 每天UTC时间0点（北京时间8点）触发
    - cron: '0 0 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 需要写权限来提交代码

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Update timestamp file
        run: |
          echo "Last update: $(date -u '+%Y-%m-%d %H:%M:%S')" > update_timestamp.txt

      - name: Commit changes
        id: commit
        run: |
          git add .
          git commit -m "🔄 自动更新仓库活跃状态 [$(date -u '+%Y-%m-%d %H:%M:%S')]" || echo "No changes to commit"

      - name: Push changes
        if: steps.commit.outputs.exit_code == 0
        run: git push
