name: Update Notion Links

on:
  workflow_dispatch: 

jobs:
  update-movie-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          
      - run: npm ci
      
      - name: Run movie updater
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_MOVIE_DATABASE_ID: ${{ secrets.NOTION_MOVIE_DATABASE_ID }}
          NOTION_MUSIC_DATABASE_ID: ${{ secrets.NOTION_MUSIC_DATABASE_ID }}
          NOTION_BOOK_DATABASE_ID: ${{ secrets.NOTION_BOOK_DATABASE_ID }}
          NOTION_GAME_DATABASE_ID: ${{ secrets.NOTION_GAME_DATABASE_ID }}
          NOTION_DRAMA_DATABASE_ID: ${{ secrets.NOTION_DRAMA_DATABASE_ID }}
          DOUBAN_USER_ID: ${{ secrets.DOUBAN_USER_ID }}
          NEODB_API_TOKEN: ${{ secrets.NEODB_API_TOKEN }}
        run: npm run patch-movie
  update-books-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          
      - run: npm ci
      
      - name: Run movie updater
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_MOVIE_DATABASE_ID: ${{ secrets.NOTION_MOVIE_DATABASE_ID }}
          NOTION_MUSIC_DATABASE_ID: ${{ secrets.NOTION_MUSIC_DATABASE_ID }}
          NOTION_BOOK_DATABASE_ID: ${{ secrets.NOTION_BOOK_DATABASE_ID }}
          NOTION_GAME_DATABASE_ID: ${{ secrets.NOTION_GAME_DATABASE_ID }}
          NOTION_DRAMA_DATABASE_ID: ${{ secrets.NOTION_DRAMA_DATABASE_ID }}
          DOUBAN_USER_ID: ${{ secrets.DOUBAN_USER_ID }}
          NEODB_API_TOKEN: ${{ secrets.NEODB_API_TOKEN }}
        run: npm run patch-book
